apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: flask-scaledobject
spec:
  scaleTargetRef:
    name: flask-app
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "50"
