apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: maoriiko/flask-app:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: flask-pvc
          mountPath: /data
        - name: dockersock
          mountPath: /var/run/docker.sock
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 500m
      volumes:
      - name: flask-pvc
        persistentVolumeClaim:
          claimName: flask-pvc
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
